src/SecondFloor.Web.Mvc/Models/AnuncianteViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using SecondFloor.I18n;

namespace SecondFloor.Web.Mvc.Models
{
    public class AnuncianteViewModels
    {
        public string Id { get; set; }

        [Display(Name = "AnuncianteViewModels_AttributeName_Responsavel",ResourceType = typeof(Resources))]
        public string NomeResponsavel { get; set; }

        [Display(Name = "AnuncianteViewModels_AttributeName_Email", ResourceType = typeof(Resources))]
        public string Email { get; set; }

        [Display(Name = "AnuncianteViewModels_AttributeName_RazaoSocial", ResourceType = typeof(Resources))]
        public string RazaoSocial { get; set; }

        [Display(Name = "AnuncianteViewModels_AttributeName_CNPJ", ResourceType = typeof(Resources))]
        public string Cnpj { get; set; }

        public ICollection<EnderecoViewModels> Enderecos { get; set; }
    }
}

src/SecondFloor.Web.Mvc/Controllers/AnuncioController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Practices.ObjectBuilder2;
using SecondFloor.DataContracts.Messages.Anunciante;
using SecondFloor.DataContracts.Messages.Anuncio;
using SecondFloor.DataContracts.Messages.Endereco;
using SecondFloor.DataContracts.Messages.Produto;
using SecondFloor.I18n;
using SecondFloor.ServiceContracts;
using SecondFloor.Web.Mvc.Models;
using SecondFloor.Web.Mvc.Services;

namespace SecondFloor.Web.Mvc.Controllers
{
    public class AnuncioController : BaseController
    {
        private readonly IAnuncioService _anuncioService;
        private readonly IProdutoService _produtoService;
        private readonly IEnderecoService _enderecoService;

        public AnuncioController(IAnuncioService anuncioService,IProdutoService produtoService, IEnderecoService enderecoService)
        {
            _anuncioService = anuncioService;
            _produtoService = produtoService;
            _enderecoService = enderecoService;
        }

        [HttpGet]
        public PartialViewResult List(string id)
        {
            var request = new EncontrarTodosAnunciosRequest() {AnuncianteId = id};
            var response = _anuncioService.EncontrarTodosAnuncios(request);

            ViewBag.Title = Resources.AnuncioController_HttpGet_List_Action_ViewBagTitle;
            ViewBag.AnuncianteId = id;

            if (!response.Success)
            {
                return PartialView("ListaAnuncioPartialView", new List<AnuncioViewModels>());
            }

            return PartialView("ListaAnuncioPartialView", response.Anuncios.ConverttoListaAnunciosViewModel());
        }

        [HttpGet]
        public PartialViewResult Create(string id)
        {
            ViewBag.Publish = false;
            ViewBag.Title = Resources.AnuncioController_HttpGet_Create_Action_ViewBagTitle;

            var enderecos = GetEnderecosPorAnunciante(id);
            var ofertas = GetProdutosPorAnunciante(id);
            var anuncio = new AnuncioViewModels()
            {
                AnuncianteId = id, 
                Enderecos = enderecos, 
                Ofertas = ofertas.ConvertListaProdutosViewModelToListaOfertasViewModel(),
            };
            
            return PartialView("AnuncioPartialView", anuncio);
        }

        [HttpPost]
        public PartialViewResult Create([Bind(Exclude = "Id")] AnuncioViewModels anuncio, FormCollection forms)
        {
            //Enderecos do Anunciante // ????
            var enderecos = GetEnderecosPorAnunciante(anuncio.AnuncianteId);
            anuncio.Enderecos = enderecos;

            //Produtos Marcados
            var produtos = GetProdutosPorAnunciante(anuncio.AnuncianteId);

            string[] ofertasCheckboxes = Request.Form["item.Checked"].Split(',');
            IList<string> ofertasChecadas = ofertasCheckboxes.Where(oferta => oferta != "false").ToList();
            IList<OfertaViewModels> produtosDisponiveis = produtos.ConvertListaProdutosViewModelToListaOfertasViewModel();
            IList<OfertaViewModels> ofertasParaPersistencia = produtosDisponiveis.Where(oferta => ofertasChecadas.Contains(oferta.Id)).ToList();
            anuncio.Ofertas = ofertasParaPersistencia;

            //Endereco Selecionado
            var endereco = GetEnderecoPorId(anuncio.EnderecoId);
            anuncio.Endereco = endereco;
            anuncio.Ofertas.ForEach(o=> o.Endereco = endereco);

            //Request
            var request = new CadastrarAnuncioRequest(){ Anuncio = anuncio.ConvertToAnuncioDto(),  AnuncianteId = anuncio.AnuncianteId };
            var response = _anuncioService.CadastrarAnuncio(request);

            ViewBag.Publish = false;
            ViewBag.Title = Resources.AnuncioController_HttpPost_Create_Action_ViewBagTitle;
            ViewBag.Message = response.Message;
            ViewBag.MessageType = response.MessageType;

            if (!response.Success)
            {
                //Lista de endereco para devolver a view
                

                response.Rules.ForEach(x => ModelState.AddModelError(x.Key, x.Value));

                //marcar as ofertas como checked
                produtosDisponiveis = GetProdutosPorAnunciante(anuncio.AnuncianteId).ConvertListaProdutosViewModelToListaOfertasViewModel();
                produtosDisponiveis.ForEach(oferta => oferta.Checked = ofertasChecadas.Contains(oferta.Id));
                //ofertas.ForEach(oferta => oferta.Id = Guid.NewGuid().ToString()); //Trocar os IDs de todas ofertas, porem perco o tracking da variacao de produto NH eh melhor !
                anuncio.Ofertas = produtosDisponiveis; //setar os itens previamente marcados

                return PartialView("AnuncioPartialView", anuncio);
            }

            return PartialView("Sucesso");
        }

        [HttpGet]
        public PartialViewResult Edit(string id)
        {
            var request = new EncontrarAnuncioRequest(){ Id = id};
            var response = _anuncioService.EncontrarAnuncioPor(request);

            ViewBag.Publish = false;
            ViewBag.Title = "Alterar Anuncio";

            if (!response.Success)
            {
                return PartialView("Error");
            }

            var anuncio = response.Anuncio.ConvertToAnuncioViewModels();
            var ofertasDoAnuncio = response.Anuncio.Ofertas.ConvertToListaOfertasViewModel(); 
            IList<string> ofertasIds = new List<string>();
            ofertasDoAnuncio.ForEach(oferta => ofertasIds.Add(oferta.Id)); //ids dos produtos que meu anuncio tem (3)

            IList<OfertaViewModels> ofertasDisponiveis = GetProdutosPorAnunciante(anuncio.AnuncianteId).ConvertListaProdutosViewModelToListaOfertasViewModel(); //produtos disponiveis (10)
            foreach (var oferta in ofertasDisponiveis)
            {
                oferta.Checked = ofertasIds.Contains(oferta.Id);
            }
            //ofertasDisponiveis.ForEach(oferta => oferta.Checked = ofertasIds.Contains(oferta.Id));
            //var enderecos = GetEnderecosPorAnunciante(anuncio.AnuncianteId);
            //anuncio.Enderecos = enderecos;
            anuncio.Ofertas = ofertasDisponiveis;

            return PartialView("AnuncioAlterarPartialView", anuncio);
        }

        [HttpPost]
        public PartialViewResult Edit(AnuncioViewModels anuncio, FormCollection forms)
        {
            //Enderecos do Anunciante // ????
            var enderecos = GetEnderecosPorAnunciante(anuncio.AnuncianteId);
            anuncio.Enderecos = enderecos;

            //Produtos Marcados
            var produtos = GetProdutosPorAnunciante(anuncio.AnuncianteId);

            string[] ofertasCheckboxes = Request.Form["item.Checked"].Split(',');
            IList<string> ofertasChecadas = ofertasCheckboxes.Where(oferta => oferta != "false").ToList();
            IList<OfertaViewModels> produtosDisponiveis = produtos.ConvertListaProdutosViewModelToListaOfertasViewModel();
            IList<OfertaViewModels> ofertasParaPersistencia = produtosDisponiveis.Where(oferta => ofertasChecadas.Contains(oferta.Id)).ToList();
            anuncio.Ofertas = ofertasParaPersistencia;

            //Endereco Selecionado
            var endereco = GetEnderecoPorId(anuncio.EnderecoId);
            anuncio.Endereco = endereco;
            anuncio.Ofertas.ForEach(o => o.Endereco = endereco);

            var request = new AlterarAnuncioRequest(){ AnuncianteId = anuncio.AnuncianteId, Anuncio = anuncio.ConvertToAnuncioDto() };
            var response = _anuncioService.AlterarAnuncio(request);

            ViewBag.Publish = false;
            ViewBag.Title = "Alterar Anuncio";
            ViewBag.Message = response.Message;
            ViewBag.MessageType = response.MessageType;

            if (!response.Success)
            {
                //Lista de endereco para devolver a view


                response.Rules.ForEach(x => ModelState.AddModelError(x.Key, x.Value));

                //marcar as ofertas como checked
                produtosDisponiveis = GetProdutosPorAnunciante(anuncio.AnuncianteId).ConvertListaProdutosViewModelToListaOfertasViewModel();
                produtosDisponiveis.ForEach(oferta => oferta.Checked = ofertasChecadas.Contains(oferta.Id));
                //ofertas.ForEach(oferta => oferta.Id = Guid.NewGuid().ToString()); //Trocar os IDs de todas ofertas, porem perco o tracking da variacao de produto NH eh melhor !
                anuncio.Ofertas = produtosDisponiveis; //setar os itens previamente marcados

                return PartialView("AnuncioAlterarPartialView", anuncio);
            }

            return PartialView("Sucesso");
        }

        public IList<ProdutoViewModels> GetProdutosPorAnunciante(string id)
        {
            var request = new EncontrarTodosProdutosRequest(){AnuncianteId = id};
            var response = _produtoService.EncontrarTodosProdutos(request);
            if (!response.Success)
            {
                //TODO: o que devolver em caso de falha
            }

            return response.Produtos.ConvertToListaProdutosViewModel();
        }

        public IList<EnderecoViewModels> GetEnderecosPorAnunciante(string id)
        {
            var request = new EncontrarTodosEnderecosRequest() { AnuncianteId = id };
            var response = _enderecoService.EncontrarTodosEnderecos(request);
            if (!response.Success)
            {
                //TODO: o que devolver em caso de falha
            }

            return response.Enderecos.ConvertToListaEnderecosViewModel();
        }

        public EnderecoViewModels GetEnderecoPorId(string id)
        {
            //Endereco selecionado para o Anuncio
            var request = new EncontrarEnderecoRequest() { Id = id };
            var response = _enderecoService.EncontrarEnderecoPor(request);
            if (!response.Success)
            {
                //TODO: retornar para a view de Novo Anuncio

src/SecondFloor.Web.Mvc/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Threading;
using System.Web.Mvc;
using SecondFloor.DataContracts.Messages.Produto;
using SecondFloor.I18n;
using SecondFloor.ServiceContracts;
using SecondFloor.Web.Mvc.Models;
using SecondFloor.Web.Mvc.Services;
using WebGrease.Css.Extensions;

namespace SecondFloor.Web.Mvc.Controllers
{
    public class ProdutoController : BaseController
    {
        private readonly IProdutoService _produtoService;

        public ProdutoController(IProdutoService produtoService)
        {
            _produtoService = produtoService;
        }

        [HttpGet]
        public PartialViewResult List(string id)
        {
            var request = new EncontrarTodosProdutosRequest() { AnuncianteId = id };
            var response = _produtoService.EncontrarTodosProdutos(request);

            ViewBag.Title = Resources.ProdutoController_HttpGet_List_Action_ViewBagTitle;
            ViewBag.AnuncianteId = id;

            if (!response.Success)
            {
                return PartialView("ListaProdutoPartialView", new List<ProdutoViewModels>());
            }

            return PartialView("ListaProdutoPartialView", response.Produtos.ConvertToListaProdutosViewModel());
        }
                
        [HttpGet]
        public PartialViewResult Create(string id)
        {
            ViewBag.Excluir = false;
            ViewBag.Title = Resources.ProdutoController_HttpGet_Create_Action_ViewBagTitle;

            var produto = new ProdutoViewModels() {AnuncianteId = id};
            produto = new ProdutoViewModels()
            {
                AnuncianteId = id,
                NomeProduto = "Esponja de Aço",
                Fabricante = "BomBrill",
                Descricao = "Lavar panelas",
                Referencia = "0001",
                Valor = ((double)3.40).ToString("C", Thread.CurrentThread.CurrentCulture) //fixed!!!
            };

            return PartialView("ProdutoPartialView", produto);
        }

        [HttpPost]
        public PartialViewResult Create([Bind(Exclude = "Id")]ProdutoViewModels produto)
        {
            var request = new CadastrarProdutoRequest() { Produto = produto.ConvertToProdutoDto(), AnuncianteId = produto.AnuncianteId };
            var response = _produtoService.CadastrarProduto(request);

            ViewBag.Excluir = false;
            ViewBag.Title = Resources.ProdutoController_HttpPost_Create_Action_ViewBagTitle;
            ViewBag.Message = response.Message;
            ViewBag.MessageType = response.MessageType;

            if (!response.Success)
            {
                response.Rules.ForEach(x=>ModelState.AddModelError(x.Key,x.Value));
                return PartialView("ProdutoPartialView", produto);
            }

            return PartialView("Sucesso");
        }

        
        [HttpGet]
        public PartialViewResult Edit(string id)
        {
            var request = new EncontrarProdutoRequest() {Id = id};
            var response = _produtoService.EncontrarProdutoPor(request);

            ViewBag.Excluir = false;
            ViewBag.Title = Resources.ProdutoController_HttpGet_Edit_Action_ViewBagTitle;

            if (!response.Success)
            {
                return PartialView("Error");
            }

            return PartialView("ProdutoPartialView", response.Produto.ConvertToProdutoViewModel());
        }
        
        [HttpPost]
        public PartialViewResult Edit(ProdutoViewModels produto)
        {
            var request = new AlterarProdutoRequest() {Produto = produto.ConvertToProdutoDto()};
            var response = _produtoService.AlterarProduto(request);

            ViewBag.Excluir = false;
            ViewBag.Title = Resources.ProdutoController_HttpPost_Edit_Action_ViewBagTitle;
            ViewBag.Message = response.Message;
            ViewBag.MessageType = response.MessageType;

            if (!response.Success)
            {
                return PartialView("ProdutoPartialView", produto);
            }

            return PartialView("Sucesso");
        }

        [HttpGet]
        public PartialViewResult Delete(string id)
        {
            var request = new EncontrarProdutoRequest() {Id = id};
            var response = _produtoService.EncontrarProdutoPor(request);

            ViewBag.Excluir = true;
            ViewBag.Title = Resources.ProdutoController_HttpGet_Delete_Action_ViewBagTitle;
            ViewBag.Message = Resources.ProdutoController_HttpGet_Delete_Action_ViewBagMessage;
            ViewBag.MessageType = "alert-danger";

            if (!response.Success)
            {
                return PartialView("Error");
            }
            
            return PartialView("ProdutoPartialView", response.Produto.ConvertToProdutoViewModel());
        }

        [HttpPost]
        public PartialViewResult Delete(ProdutoViewModels produto)
        {
            var request = new ExcluirProdutoRequest() { Id = produto.Id };
            var response = _produtoService.ExcluirProduto(request);

            ViewBag.Excluir = true;
            ViewBag.Title = Resources.ProdutoController_HttpPost_Delete_Action_ViewBagTitle;
            ViewBag.Message = response.Message;
            ViewBag.MessageType = response.MessageType;

            if (!response.Success)
            {
                return PartialView("Error");
            }

            return PartialView("Sucesso");
        }
    }
}

src/SecondFloor.Web.Mvc/Views/Anunciante/AnuncianteDetalhesPartialView.cshtml
@model SecondFloor.Web.Mvc.Models.AnuncianteViewModels

<div>
    <h4>@ViewBag.Title</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeResponsavel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeResponsavel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RazaoSocial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RazaoSocial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cnpj)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cnpj)
        </dd>
    </dl>
</div>
<p>
    <button type="button" onclick="ajaxModalFormOpenHandler(this)" class="btn btn-xs btn-warning"
            data-url="/Anunciante/Edit/@Html.DisplayFor(id => Model.Id)"
            data-url-content-update="/Anunciante/Detail/@Html.DisplayFor(id => Model.Id)"
            data-content-update-id="#conteudoAnuncianteDetalhe">
        <i class="glyphicon glyphicon-pencil"></i>
    </button>
</p>

src/SecondFloor.Web.Mvc/Views/Anunciante/AnunciantePartialView.cshtml
@using SecondFloor.I18n
@model SecondFloor.Web.Mvc.Models.AnuncianteViewModels

<div class="modal-dialog">
    <div class="modal-content">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 id="myModalLabel" class="modal-title">&nbsp;@ViewBag.Title</h4>
        </div>
        @if (!string.IsNullOrEmpty(ViewBag.MessageType))
        {
            <div class="alert @ViewBag.MessageType fade in">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <small>@Html.Raw(ViewBag.Message)</small>
            </div>
        }

        <div id="myModalBody" class="modal-body">
            <div id="conteudo-modal">
                @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "myModal" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.NomeResponsavel, htmlAttributes: new { @class = "control-label col-md-3" })
                            @if (!ViewBag.Excluir)
                            {
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.NomeResponsavel, new {htmlAttributes = new {@class = "form-control"}})
                                    @Html.ValidationMessageFor(model => model.NomeResponsavel, "", new {@class = "text-danger"})
                                </div>
                            }
                            else
                            {
                                <div class="col-md-6">
                                    @Html.DisplayFor(model=>model.NomeResponsavel)
                                </div>
                            }
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
                            @if(!ViewBag.Excluir)
                            {
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                            }
                            else
                            {
                                <div class="col-md-6">
                                    @Html.DisplayFor(model=>model.Email)
                                </div>
                            }
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.RazaoSocial, htmlAttributes: new { @class = "control-label col-md-3" })
                            @if (!ViewBag.Excluir)
                            {
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.RazaoSocial, new {htmlAttributes = new {@class = "form-control"}})
                                    @Html.ValidationMessageFor(model => model.RazaoSocial, "", new {@class = "text-danger"})
                                </div>
                            }
                            else
                            {
                                <div class="col-md-6">
                                    @Html.DisplayFor(model=>model.NomeResponsavel)
                                </div>
                            }
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Cnpj, htmlAttributes: new { @class = "control-label col-md-3" })
                            @if (!ViewBag.Excluir)
                            {
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Cnpj, new {htmlAttributes = new {@class = "form-control"}})
                                    @Html.ValidationMessageFor(model => model.Cnpj, "", new {@class = "text-danger"})
                                </div>
                            }
                            else
                            {
                                <div class="col-md-6">
                                    @Html.DisplayFor(model=>model.Cnpj)
                                </div>
                            }
                        </div>

                        <!--<div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>-->
                    </div>
                }
            </div>
        </div>
        <div class="modal-footer form-horizontal">
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal" aria-hidden="true">@Resources.View_Anunciante_AnunciantePartialView_Botao_Cancelar</button>
            <a id="criarAnunciante" onclick="ajaxFormSubmit(this)" href="#" role="button" class="btn btn-sm btn-danger">@Resources.View_Anunciante_AnunciantePartialView_Botao_Salvar</a>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

src/SecondFloor.Web.Mvc/Views/Anunciante/AnuncianteSucesso.cshtml
Sucesso no cadastro veja o email e efetue login.

src/SecondFloor.Web.Mvc/Views/Anunciante/Detalhes.cshtml
@using SecondFloor.I18n
@model SecondFloor.Web.Mvc.Models.AnuncianteViewModels

<div id="conteudoAnuncianteDetalhe">
    @{
        Html.RenderPartial("AnuncianteDetalhesPartialView");
    }
</div>

<hr/>

<ul id="myTab" class="nav nav-tabs" role="tablist">
    <li id="tab-endereco" class="active" >
        <a href="#conteudoAnuncianteEndereco" role="tab" data-toggle="tab"
           data-url-content-update="/Endereco/List/@Html.DisplayFor(m=>m.Id)"
           data-content-update-id="#conteudoAnuncianteEndereco"
           onclick="ajaxUpdateContent(this)">@Resources.View_Anunciante_Detalhes_Tab_Endereco</a>
    </li>
    <li id="tab-produto">
        <a href="#conteudoAnuncianteProduto" role="tab" data-toggle="tab"
           data-url-content-update="/Produto/List/@Html.DisplayFor(m=>m.Id)"
           data-content-update-id="#conteudoAnuncianteProduto"
           onclick="ajaxUpdateContent(this)">@Resources.View_Anunciante_Detalhes_Tab_Produto</a>
    </li>
    <li id="tab-anuncio">
        <a href="#conteudoAnuncianteAnuncio" role="tab" data-toggle="tab"
           data-url-content-update="/Anuncio/List/@Html.DisplayFor(m=>m.Id)"
           data-content-update-id="#conteudoAnuncianteAnuncio"
           onclick="ajaxUpdateContent(this)">@Resources.View_Anunciante_Detalhes_Tab_Anuncio</a>
    </li>
</ul>

<div id="MyTabContent" class="tab-content">
    <!--<hr />-->
    <div id="conteudoAnuncianteEndereco" class="tab-pane fade in active">
        @{Html.RenderAction("List", "Endereco", new { Id = Model.Id });}
    </div>
    
    <!--<hr />-->
    <div id="conteudoAnuncianteProduto" class="tab-pane fade">
        @{Html.RenderAction("List", "Produto", new { Id = Model.Id });}
    </div>
    
    <!--<hr />-->
    <div id="conteudoAnuncianteAnuncio" class="tab-pane fade">
        @{Html.RenderAction("List", "Anuncio", new { Id = Model.Id });}

        @*<h4>Lista de Anuncios</h4>
        <p>
            <button type="button" onclick="ajaxModalFormOpenHandler(this)" class="btn btn-sm btn-default disabled"
                    data-url="/Anuncio/Create/@ViewBag.AnuncianteId"
                    data-url-content-update="/Anuncio/List/@ViewBag.AnuncianteId"
                    data-content-update-id="#conteudoAnuncianteAnuncio">
                Novo Anuncio
            </button>
        </p>
        <table class="table table-striped table-bordered table-hover table-condensed">
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Data Inicio</th>
                    <th>Data Fim</th>
                    <th>Nome dos Produtos Anunciados</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="text-center"><i class="glyphicon glyphicon-ok"></i></td>
                    <td>20/10/2014</td>
                    <td>26/10/2014</td>
                    <td>Prod1 Prod2 Prod3 Prod4 Prod5 Prod5 Prod7 Prod8 </td>
                    <td class="text-center"><button type="button" class="btn btn-sm btn-danger disabled">Alterar</button></td>
                </tr>
                <tr>
                    <td class="text-center"><i class="glyphicon glyphicon-ok"></i> <i class="glyphicon glyphicon-dashboard"></i></td>
                    <td>27/10/2014</td>
                    <td>02/11/2014</td>
                    <td>Prod2 Prod4 Prod7 Prod8 Prod10 Prod11 Prod12 Prod13 </td>
                    <td class="text-center"><button type="button" class="btn btn-sm btn-warning disabled">Alterar</button></td>
                </tr>
                <tr>
                    <td class="text-center"><i class="glyphicon glyphicon-dashboard"></i></td>
                    <td>03/11/2014</td>
                    <td>09/11/2014</td>
                    <td>Prod1 Prod2 Prod3 Prod4 Prod5 Prod5 Prod7 Prod8 </td>
                    <td class="text-center"><button type="button" class="btn btn-sm btn-warning disabled">Alterar</button></td>
                </tr>
                <tr>
                    <td class="text-center"><i class="glyphicon glyphicon glyphicon-warning-sign"></i></td>
                    <td>10/11/2014</td>
                    <td>16/11/2014</td>
                    <td>Prod1 Prod2 Prod3 Prod4 Prod5 Prod5 Prod7 Prod8 </td>
                    <td class="text-center"><button type="button" class="btn btn-sm btn-success disabled">Publicar</button></td>
                </tr>

            </tbody>
        </table>
        <p>Lista de Anuncios publicados ou agendados</p>*@
    </div>
</div>

src/SecondFloor.Web.Mvc/Views/Anunciante/Lista.cshtml
@model IEnumerable<SecondFloor.Web.Mvc.Models.AnuncianteViewModels>


<h4>@ViewBag.Title</h4>

<div id="conteudoAnunciante">
    @{Html.RenderPartial("ListaAnunciantePartialView", Model);}
</div>